name: 'Setup Kubernetes'
description: 'Install Kubernetes distribution (kubeadm, k3s, k0s, rke2, or microk8s)'
inputs:
  distribution:
    description: 'Kubernetes distribution to install (kubeadm, k3s, k0s, rke2, microk8s)'
    required: true
    default: 'kubeadm'
  extra-params:
    description: 'Extra parameters for the distribution installer'
    required: false
    default: ''
  container-runtime:
    description: 'Container runtime for kubeadm (containerd or crio) - only for kubeadm'
    required: false
    default: 'containerd'
  runtime-version:
    description: 'Container runtime version - only for kubeadm'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Setup Kubernetes
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        case "${{ inputs.distribution }}" in
          kubeadm)
            ${{ github.action_path }}/../../scripts/k8s-operations.sh setup kubeadm \
              ${{ inputs.container-runtime }} \
              ${{ inputs.runtime-version }}
            ;;
          k3s)
            ${{ github.action_path }}/../../scripts/k8s-operations.sh setup k3s \
              ${{ inputs.extra-params }}
            ;;
          k0s)
            ${{ github.action_path }}/../../scripts/k8s-operations.sh setup k0s \
              ${{ inputs.extra-params }}
            ;;
          rke2)
            ${{ github.action_path }}/../../scripts/k8s-operations.sh setup rke2
            ;;
          microk8s)
            ${{ github.action_path }}/../../scripts/k8s-operations.sh setup microk8s
            ;;
          *)
            echo "❌ Unknown distribution: ${{ inputs.distribution }}"
            exit 1
            ;;
        esac
