name: Run Test Pod
description: Deploy and verify a test pod using Kata runtime

inputs:
  runtime-class:
    description: 'RuntimeClass to use for the test pod'
    required: true
  namespace:
    description: 'Kubernetes namespace for test pod'
    required: false
    default: 'default'
  pod-name:
    description: 'Name of the test pod'
    required: false
    default: 'kata-test-pod'
  timeout:
    description: 'Timeout for pod to become ready'
    required: false
    default: '5m'

outputs:
  pod-status:
    description: 'Final status of the test pod'
    value: ${{ steps.check-status.outputs.status }}

runs:
  using: composite
  steps:
    - name: Verify cluster health
      shell: bash
      run: ${{ github.action_path }}/../../scripts/k8s-operations.sh pod verify-cluster-health

    - name: Create test pod
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod create \
          ${{ inputs.pod-name }} \
          ${{ inputs.runtime-class }} \
          ${{ inputs.namespace }}

    - name: Wait for pod
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod wait \
          ${{ inputs.pod-name }} \
          ${{ inputs.namespace }} \
          300

    - name: Check pod status
      id: check-status
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod check-status \
          ${{ inputs.pod-name }} \
          ${{ inputs.namespace }}

    - name: Show pod details
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod show-details \
          ${{ inputs.pod-name }} \
          ${{ inputs.namespace }}

    - name: Show pod logs
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod show-logs \
          ${{ inputs.pod-name }} \
          ${{ inputs.namespace }}

    - name: Verify Kata runtime is used
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod verify-runtime \
          ${{ inputs.pod-name }} \
          ${{ inputs.runtime-class }} \
          ${{ inputs.namespace }}

    - name: Cleanup test pod
      if: always()
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh pod cleanup \
          ${{ inputs.pod-name }} \
          ${{ inputs.namespace }}
