name: Install Helm Chart
description: Install the Confidential Containers Helm chart with various configurations

inputs:
  release-name:
    description: 'Helm release name'
    required: false
    default: 'coco'
  namespace:
    description: 'Kubernetes namespace'
    required: false
    default: 'kube-system'
  extra-args:
    description: 'Extra Helm install arguments (e.g., --set flags)'
    required: false
    default: ''
  values-file:
    description: 'Path to values file (optional)'
    required: false
    default: ''
  wait-timeout:
    description: 'Timeout for helm install --wait'
    required: false
    default: '15m'

outputs:
  installed:
    description: 'Whether installation succeeded'
    value: ${{ steps.install.outputs.result }}

runs:
  using: composite
  steps:
    - name: Update Helm dependencies
      shell: bash
      run: ${{ github.action_path }}/../../scripts/helm-operations.sh update-dependencies .

    - name: Validate chart
      shell: bash
      run: ${{ github.action_path }}/../../scripts/helm-operations.sh validate .

    - name: Install chart
      id: install
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/helm-operations.sh install \
          ${{ inputs.release-name }} \
          --namespace ${{ inputs.namespace }} \
          --chart-dir . \
          --wait-timeout ${{ inputs.wait-timeout }} \
          ${{ inputs.values-file && format('--values-file {0}', inputs.values-file) || '' }} \
          ${{ inputs.extra-args && format('--extra-args "{0}"', inputs.extra-args) || '' }}
