name: Verify Deployment
description: Verify kata-deploy daemonset and RuntimeClasses are created

inputs:
  namespace:
    description: 'Kubernetes namespace where chart is installed'
    required: false
    default: 'coco-system'
  expected-runtime-classes:
    description: 'Space-separated list of expected RuntimeClass names'
    required: false
    default: 'kata-qemu-coco-dev'
  daemonset-timeout:
    description: 'Timeout for daemonset to become ready'
    required: false
    default: '15m'
  daemonset-label:
    description: 'Label selector for kata-deploy daemonset (e.g., name=kata-as-coco-runtime or name=kata-as-coco-runtime-for-ci)'
    required: false
    default: 'name=kata-as-coco-runtime'

outputs:
  verification-status:
    description: 'Overall verification status'
    value: ${{ steps.verify.outputs.status }}

runs:
  using: composite
  steps:
    - name: Wait for kata-deploy daemonset
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh deployment wait-daemonset \
          --namespace ${{ inputs.namespace }} \
          --label ${{ inputs.daemonset-label }} \
          --timeout ${{ inputs.daemonset-timeout }}

    - name: Verify daemonset status
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh deployment verify-daemonset \
          --namespace ${{ inputs.namespace }} \
          --label ${{ inputs.daemonset-label }}

    - name: Show daemonset logs
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh deployment show-logs \
          --namespace ${{ inputs.namespace }} \
          --label ${{ inputs.daemonset-label }} \
          --tail 50

    - name: Verify RuntimeClasses
      id: verify
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh deployment verify-runtimeclasses \
          ${{ inputs.expected-runtime-classes }} \
          --timeout 180

    - name: Show RuntimeClass details
      shell: bash
      run: |
        ${{ github.action_path }}/../../scripts/k8s-operations.sh deployment show-runtimeclass-details \
          ${{ inputs.expected-runtime-classes }}

